### ISSUE TITLE
Direct missiles do not take into account target motion when calculating their initial trajectory

### ISSUE THREAD

**Issue by Cebasiz** [stackcollision/Nebulous-BugReporting#172]
**Describe the bug**
When launching a missile with DIRECT guidance, the missile does not put in lead based on the target's course and speed. this can result in misses at medium range against fast targets. IIRC, it didn't used to be this way.

**To Reproduce**
1. Fire direct missile at target
2. Observe course not taking into account target motion, sometimes resulting in missing the seeker basket.

**Expected behavior**
DIRECT missiles should calculate an intercept based on target course/speed. "Seeker basket misses" should only occur if the target is uncertain or if the target changes course to such an extent that the missile misses the basket.

[DIRECT no motion prediction.webm](https://user-images.githubusercontent.com/10738550/206081658-e4649aa4-d46e-434e-9470-e397d6d0c576.webm)

^vid above, despite target being in constant motion, missiles firing at target's current position only and only correct back on after seeker acq. Earlier in that match I missed a target at 9km because it's movement brought it out of the seeker basket despite it not changing course during the flyout.

**Comment by Cebasiz** [comment]
As an addendum to this, target ambiguity isn't being factored in either. Firing at a track with a 2km (EWR) ambiguity results in missiles that are launched directly at the target without factoring in the tracks "reported position" at the moment of the launch. This makes firing missiles at EWR tracks possible where they probably shouldn't be unless the target is much closer than the EWR max range.

**Comment by xlwoon** [comment]
I confirm this, I tested it myself by firing cruise-capable missiles and direct-only missiles of otherwise identical configuration simultaneously directly on the radar contact of a moving target (steady course), and observed that the cruise-capable missiles fly to an intercept while the direct-only missiles fly to a different course, probably at the position of the target at the moment of launch without accounting for velocity.

I am also of the opinion that this should not be the case, as the initial course the launching ship gives should not have anything to do with the missile's onboard avionics, just with the accuracy with which the launching ship is tracking the target.

The way it is currently implemented, every ballistic weapon that is fired on a track uses computed intercept point except for non-cruise missiles, which also feels wrong.
