### ISSUE TITLE
Validated missiles go for jamming false targets when set to REJECT unvalidated

### ISSUE THREAD

**Issue by Cebasiz** [stackcollision/Nebulous-BugReporting#211]
**Describe the bug**
Validated missiles go for jamming false targets when set to REJECT unvalidated targets

**To Reproduce**
Make a missile with a non-radar validator set to REJECT (I tested CMD and EO) when equipped with DIRECT guidance (seeker on at launch)
watch it chase unvalidated tracks off target into deep space the majority of the time.

**Expected behavior**
Missile should continue straight on course and not chase unvalidated targets.

**Comment by Sumikae** [comment]
I've also experienced this issue. The missiles go for presumably spoofed tracks instead of flying straight. I've attached a video of Radar guided Command validated S2 missiles with reject invalid targets.

[command val test.zip](https://github.com/stackcollision/Nebulous-BugReporting/files/10751982/command.val.test.zip)
