### ISSUE TITLE
Missile sprint stage activating early

### ISSUE THREAD

**Issue by AhriiIsHot** [stackcollision/Nebulous-BugReporting#30]
**Describe the bug**
Upon firing my "Huntress" missiles at a target about 4 KM away on Shooting range, the sprint stage activates almost immediately and burns up the missile's fuel before it gets remotely near the target.

**To Reproduce**
1. Load up a 1v1 control on shooting range
2. Issue a jam command with the jammers on the enemy ship and lock it
3. do not move, issue fire command for the Huntress missile, add target twice
4. Wait until the missile fires, MLS3 has to reload.

**Expected behavior**
For the missile to calculate its sprint distance so the warhead hits its target instead of falling short

**Additional context**
Done against a ship of the same fleet.

**Attachments**
[1x atlas missile.zip](https://github.com/stackcollision/Nebulous-BugReporting/files/9036243/1x.atlas.missile.zip)

**Comment by BearSlayer117** [comment]
So I am also having this issue with my missiles but I am not using any jammers at all. The missile I have is supposed to activate sprint stage at 2.5km with a range of 2.9km but instead of waiting to get into that range the moment it leaves the tube it is instantly activating and going into sprint and then detonates short of the target because its at about 4km
[SGM-H-300 Atlatl.zip](https://github.com/stackcollision/Nebulous-BugReporting/files/9234848/SGM-H-300.Atlatl.zip)
