### ISSUE TITLE
NRE Cataclysm when opening up the Escape menu in Skirmish. 

### ISSUE THREAD

**Issue by Dargaribdus** [stackcollision/Nebulous-BugReporting#548]
**Describe the bug**
Unable to Exit to Main Menu from Skirmish map; generates massive wall of red text. 

Reproduction steps
1. Load the CQ template below OR the save. 
2. Drop down into a skirmish match with a TG that contains both the Raines and Sprinter templates.
3. Attempt to Exit to Main Menu.

**Additional context**
I was attempting to help Lobster track down some weird template behavior with missiles being deleted out of the fleet editor. I used the templates that were a problem in main neb on the Conquest Navy Designer. Everything was fine, missiles were properly spawning and being available for use all the way down to the skirmish map. Then this happened when I attempted to leave the skirmish game. I then left the escape menu and could no longer open it. I was forced to ALT + F4 out of the game. 

**Attachments**
![image](https://github.com/stackcollision/Nebulous-BugReporting/assets/163589943/15102eea-5d1a-4038-a461-1b551094b6bd)
[Player.log](https://github.com/stackcollision/Nebulous-BugReporting/files/14653932/Player.log)
[torp weirdness testing-93HrXZfw0EOo9jWkxdzr5Q.zip](https://github.com/stackcollision/Nebulous-BugReporting/files/14654133/torp.weirdness.testing-93HrXZfw0EOo9jWkxdzr5Q.zip)
[Missile Weirdness Test.zip](https://github.com/stackcollision/Nebulous-BugReporting/files/14654140/Missile.Weirdness.Test.zip)
[Player.log](https://github.com/stackcollision/Nebulous-BugReporting/files/14654170/Player.log)

**Comment by ShadowLotus232** [comment]
Addendum: Bug can be reproduced by exiting a skirmish period. The ships don't matter, the scenario doesn't matter, just exit a skirmish as the host (at least in single player, I haven't tested multiplayer but if I'm right it exists there too).

The issue comes from `Game.SkirmishGameHost.CoroutineClusterShips()`. Exiting the skirmish destroys all the ShipController objects in `Game.SkirmishGameHost._allShips`, but then the coroutine that had yielded regains control and tries to find the distance between those, now destroyed, transforms, causing the NRE.

...At least I'm decently confident that's what's happening ^^;

**Comment by ShadowLotus232** [comment]
Same issue as #541 oops
