### ISSUE TITLE
Game 27: Newly Constructed Ships Stuck in Graving

### ISSUE THREAD

**Issue by sarnyarn** [stackcollision/Nebulous-BugReporting#630]
**Describe the bug**
Turn 16 
After producing two new construction CH designs (designs not used in the initial set up), they remained in graving docks for an extended period (Oct 15 construction date; new graving date of Nov 7). I was unable to issue any kind of orders or remove them from said graving.

**To Reproduce**
1. Create new construction of a newly researched design.
2. Wait for production to complete.
3. Check Shipyard berthing schedule
4. See bug

**Expected behavior**
For the newly constructed ships to be able to be used/sent to different piers for rearm/refuel.

**Additional context**
Comment made on issue https://github.com/stackcollision/Nebulous-BugReporting/issues/478#issuecomment-2065536541 is in reference to these two newly built ships. 

**Attachments**
Screenshot of issue:
![neb new construction bug](https://github.com/stackcollision/Nebulous-BugReporting/assets/163873847/6867ea1f-b064-444b-9250-b983bd4e40d1)

Save:
[Small_CQ_MP_Test-aEr4P75yoEu_RVrCjKyCRA.zip](https://github.com/stackcollision/Nebulous-BugReporting/files/15031922/Small_CQ_MP_Test-aEr4P75yoEu_RVrCjKyCRA.zip)

**Comment by Snowblind111** [comment]
I've seen this bug manifest in slightly different ways, but the core of the issue is that non-starting designs cannot be reliably fresh build. Sometimes the ship gets added to graving and is stuck there, sometimes it is never added at all. Occasionally it works fine for some reason.

Hopefully, this series of repo steps will provide a consistent way of reproducing the behavior.

1. Start a fresh conq game with default settings, setting up both teams with different 75k fleets.
2. Upon starting, load a new design (a CH in my case), set it to be researched as a new construction.
3. Execute turns until the shipyard has processed all starting ships, then order all ships to leave the shipyard.
4. Go to the production tab and click build on a pre-existing design (another CH in my case), and then immediately click build on the newly researched design.
5. Hit execute turn. The old design will be added to graving, but the new design will not. Both ships will exist in the berthing schedule. An error will be thrown.

Here is the thrown error:
```

Work at pier 1 berth 0 for ship Under Construction Ship(Clone) (Conquest.Production.UnderConstructionShip) has begun.
Work at pier 1 berth 1 for ship Under Construction Ship(Clone) (Conquest.Production.UnderConstructionShip) has begun.
Exception while performing simulation work at a berth on station NAVSHPYD Amethyst: System.NullReferenceException: Object reference not set to an instance of an object
  at Conquest.Teams.TeamBlueprintCollection.CreateNewShipRecord (Conquest.Teams.TeamBlueprintCollection+ShipBPInfo bp) [0x00065] in D:\Projects\Unity\Nebulous Conquest\Assets\Source\Conquest\Teams\TeamBlueprintCollection.cs:696 
  at Conquest.Production.UnderConstructionShip.Conquest.Stations.IStationScheduleWorkSubject.OnWorkStarted () [0x00012] in D:\Projects\Unity\Nebulous Conquest\Assets\Source\Conquest\Production\UnderConstructionShip.cs:200 
  at Conquest.Stations.SpaceStation.HandlePierWorkStarted (System.Int32 pier, System.Int32 berth, Conquest.Stations.IStationScheduleWorkSubject ship) [0x00033] in D:\Projects\Unity\Nebulous Conquest\Assets\Source\Conquest\Stations\SpaceStation.cs:1153 
  at Conquest.Stations.SpaceStation+<>c__DisplayClass135_1.<BuildStation>b__1 (Conquest.Stations.IStationScheduleWorkSubject ship) [0x00001] in D:\Projects\Unity\Nebulous Conquest\Assets\Source\Conquest\Stations\SpaceStation.cs:280 
  at Conquest.Scheduling.Schedule`1[TSkedSubject].SimStep () [0x00038] in D:\Projects\Unity\Nebulous Conquest\Assets\Source\Conquest\Scheduling\Schedule.cs:127 
  at Conquest.Stations.SpaceStation.SimulationStep (System.Int64 stepSize, System.Int64 time, Conquest.IConquestEventScheduler events) [0x00045] in D:\Projects\Unity\Nebulous Conquest\Assets\Source\Conquest\Stations\SpaceStation.cs:534 
UnityEngine.StackTraceUtility:ExtractStackTrace () (at C:/buildslave/unity/build/Runtime/Export/Scripting/StackTrace.cs:37)
UnityEngine.DebugLogHandler:LogFormat (UnityEngine.LogType,UnityEngine.Object,string,object[])
UnityEngine.Logger:Log (UnityEngine.LogType,object)
UnityEngine.Debug:LogError (object)
Conquest.Stations.SpaceStation:SimulationStep (long,long,Conquest.IConquestEventScheduler) (at D:/Projects/Unity/Nebulous Conquest/Assets/Source/Conquest/Stations/SpaceStation.cs:536)
Conquest.Map.StarSystemObject:SimulationStep (long,long,Conquest.IConquestEventScheduler) (at D:/Projects/Unity/Nebulous Conquest/Assets/Source/Conquest/Map/StarSystemObject.cs:262)
Conquest.Map.StarSystemObject:SimulationStep (long,long,Conquest.IConquestEventScheduler) (at D:/Projects/Unity/Nebulous Conquest/Assets/Source/Conquest/Map/StarSystemObject.cs:258)
Conquest.Map.StarSystemObject:SimulationStep (long,long,Conquest.IConquestEventScheduler) (at D:/Projects/Unity/Nebulous Conquest/Assets/Source/Conquest/Map/StarSystemObject.cs:258)
Conquest.Map.StarSystemMap:SimulationStep (long,long,Conquest.IConquestEventScheduler) (at D:/Projects/Unity/Nebulous Conquest/Assets/Source/Conquest/Map/StarSystemMap.cs:142)
Conquest.ConquestGameManager/<CoroutineExecuteTurn>d__168:MoveNext () (at D:/Projects/Unity/Nebulous Conquest/Assets/Source/Conquest/ConquestGameManager.cs:1710)
Utility.CoroutineUtils/<RunThrowingIterator>d__1:MoveNext () (at D:/Projects/Unity/Nebulous Conquest/Assets/Source/Utility/CoroutineUtils.cs:50)
UnityEngine.SetupCoroutine:InvokeMoveNext (System.Collections.IEnumerator,intptr) (at C:/buildslave/unity/build/Runtime/Export/Scripting/Coroutines.cs:17)

(Filename: D:/Projects/Unity/Nebulous Conquest/Assets/Source/Conquest/Stations/SpaceStation.cs Line: 536)
```

Here is the ship+teams used to repo the above (opfor fleet is for the CPU team B).
[Saves.zip](https://github.com/stackcollision/Nebulous-BugReporting/files/15075256/Saves.zip)
